import AntdRegistry from '@/libs/AntdRegistry';
import StyledComponentsRegistry from '@/libs/StyledComponentsRegistry';
import { App } from 'antd';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import QueryClientProviders from '@/libs/QueryClientProviders';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryClientProviders>
          <StyledComponentsRegistry>
            <AntdRegistry>
              <App>{children}</App>
            </AntdRegistry>
          </StyledComponentsRegistry>
        </QueryClientProviders>
      </body>
    </html>
  );
}

